_wandb:
    value:
        cli_version: 0.19.9
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
                - 105
            "3":
                - 7
                - 16
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.29.0
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
audioldm_model:
    value: audioldm-m-full
batch_size:
    value: 4
continue_from:
    value: null
dataset_path:
    value: audioldm/qvim/data
debug:
    value: true
duration:
    value: 10
early_stopping_min_delta:
    value: 0
early_stopping_patience:
    value: 10
final_eval_dataset:
    value: val
fmax:
    value: null
fmax_aug_range:
    value: 2000
fmin:
    value: 0
fmin_aug_range:
    value: 10
freqm:
    value: 8
hop_size:
    value: 320
initial_tau:
    value: 0.07
lr_schedule:
    value: cosine
max_items:
    value: 50
max_lr:
    value: 0.0003
min_lr:
    value: 2.5e-05
model_save_path:
    value: audioldm/qvim/models_clap_aligned
n_epochs:
    value: 100
n_fft:
    value: 1024
n_mels:
    value: 128
num_workers:
    value: 2
output_dim:
    value: 512
pin_memory:
    value: true
pretrained_name:
    value: mn10_as
project:
    value: qvim-clap-alignment
rampdown_epochs:
    value: 22
random_seed:
    value: 42
sample_rate:
    value: 32000
tau_trainable:
    value: true
timem:
    value: 300
val_split:
    value: 0.15
warmup_epochs:
    value: 1
weight_decay:
    value: 0.0003
window_size:
    value: 800
